name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator-cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
