name: "Build"
on:
  pull_request:
  push:
jobs:
  release-librop:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build release-librop.nix

  release-libc:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build release-libc.nix
   
  debug-librop:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build debug-librop.nix
  
  debug-libc:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build debug-libc.nix


name: "Tests"
on:
  pull_request:
  push:
jobs:
  release-librop:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell release-librop.nix && eval "$unpackPhase" && eval "patchPhase" && eval "$configurePhase" && cd lib/Target/X86/ropfuscator && ctest
  
  release-libc:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell release-libc.nix && eval "$unpackPhase" && eval "patchPhase" && eval "$configurePhase" && cd lib/Target/X86/ropfuscator && ctest

  debug-librop:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell debug-librop.nix && eval "$unpackPhase" && eval "patchPhase" && eval "$configurePhase" && cd lib/Target/X86/ropfuscator && ctest
 
  debug-libc:
    runs-on: ubuntu-latest
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: ropfuscator
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell debug-libc.nix && eval "$unpackPhase" && eval "patchPhase" && eval "$configurePhase" && cd lib/Target/X86/ropfuscator && ctest
