name: "Build"
on:
  pull_request:
  push:
jobs:
  build-release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix build -L

  tests-release:
    runs-on: self-hosted
    needs: build-release
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: nix build .#tests -L
