name: "Build"
on:
  pull_request:
  push:
jobs:
  build-release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L

  test-release:
    runs-on: self-hosted
    needs: build-release
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#testsBuild -L
