name: "Build"
on:
  pull_request:
  push:
jobs:
  build-release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: nix build -L

  tests-release:
    runs-on: self-hosted
    needs: build-release
    steps:
      - uses: actions/checkout@v2
      - run: nix flake update
      - run: nix build .#tests -L

  build-debug:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: nix build .#debug -L
