name: "Packages"
on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed
jobs:
  llvmZero:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmZero -L

  llvmOne:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmOne -L
  
  llvmTwo:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmTwo -L

  llvmThree:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmThree -L
