name: "Packages"
on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed
jobs:
  helloVanilla:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#helloVanilla -L
  
  helloRopOnly:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#helloRopOnly -L
  
  helloHalfAddresses:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#helloHalfAddresses -L
  
  helloAllAddresses:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#helloAllAddresses -L
  
  helloFull:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#helloFull -L
  
  coreutilsVanilla:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#coreutilsVanilla -L
  
  coreutilsRopOnly:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#coreutilsRopOnly -L
  
  coreutilsHalfAddresses:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#coreutilsHalfAddresses -L
  
  coreutilsAllAddresses:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#coreutilsAllAddresses -L
  
  coreutilsFull:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#coreutilsFull -L

  llvmVanilla:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmVanilla -L

  llvmRopOnly:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmRopOnly -L

  llvmHalfAddresses:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmHalfAddresses -L
  
  llvmAllAddresses:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmAllAddresses -L

  llvmFull:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v10
        with:
          name: ropfuscator
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#llvmFull -L
