name: "Test"
on:
  pull_request:
  push:
jobs:
  release:
    runs-on: self-hosted
    steps:
    - name: Submodules checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ROPFUSCATOR_PAT }}
        submodules: recursive
    - uses: actions/checkout@v2.4.0
      #    - uses: cachix/install-nix-action@v15
      #    - uses: cachix/cachix-action@v10
      #      with:
      #        name: ropfuscator
      #        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell release.nix --run 'eval "$unpackPhase" && patchPhase && eval "$configurePhase" && cd lib/Target/X86/ropfuscator/tests && ctest'
  
      #  debug:
      #    runs-on: self-hosted
      #    steps:
      #    - name: Submodules checkout
      #      uses: actions/checkout@v2
      #      with:
      #        token: ${{ secrets.ROPFUSCATOR_PAT }}
      #        submodules: recursive
      #    - uses: actions/checkout@v2.4.0
      #      #    - uses: cachix/install-nix-action@v15
      #      #    - uses: cachix/cachix-action@v10
      #      #      with:
      #      #        name: ropfuscator
      #      #        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      #    - run: nix-shell debug.nix --run 'eval "$unpackPhase" && patchPhase && eval "$configurePhase" && cd lib/Target/X86/ropfuscator/tests && ctest'
